wip

diff --git a/.github/workflows/phpstan.yml b/.github/workflows/phpstan.yml
--- a/.github/workflows/phpstan.yml
+++ b/.github/workflows/phpstan.yml
@@ -95,18 +95,10 @@ jobs:
     steps:
       - name: Generate introduced-errors.json
         run: |
-          echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}'
-          echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}'
-          jq -s 'def errs($json): $json.files|to_entries|map(.key as $file|.value.messages[]|{file:$file}+{message:.message,line:.line,ignorable:.ignorable,identifier:.identifier}); (.[1]|errs(.)) as $targetErrors|(.[0]|errs(.)) as $prErrors|$prErrors|map(select(( $targetErrors|index(.) )==null))' \
-            <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') \
-            <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') \
-            > introduced-errors.json || true
+          jq -s 'def errs($j): $j.files | to_entries | map({file: .key} + .value.messages[]); (.[0] | errs(.)) as $pr | (.[1] | errs(.)) as $base | $pr | map(select(( $base | index(.) ) == null))' <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') > introduced-errors.json || true
       - name: Generate removed-errors.json
         run: |
-          jq -s 'def errs($json): $json.files|to_entries|map(.key as $file|.value.messages[]|{file:$file}+{message:.message,line:.line,ignorable:.ignorable,identifier:.identifier}); (.[1]|errs(.)) as $targetErrors|(.[0]|errs(.)) as $prErrors|$targetErrors|map(select(( $prErrors|index(.) )==null))' \
-            <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') \
-            <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') \
-            > removed-errors.json || true
+          jq -s 'def errs($j): $j.files | to_entries | map({file: .key} + .value.messages[]); (.[0] | errs(.)) as $pr | (.[1] | errs(.)) as $base | $base | map(select(( $pr | index(.) ) == null))' <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') > removed-errors.json || true
       - name: Show summary of deltas
         run: |
           echo "Introduced files/errors:"
@@ -127,7 +119,7 @@ jobs:
             fi
             echo "| File | Line | Message |"
             echo "| ---- | ----: | ------- |"
-            echo "$json_array" | jq -r '.[] | "| \(.file|gsub("\\|"; "\\\\|")) | \(.line) | \(.message|gsub("\\|"; "\\\\|")) |"'
+            echo "$json_array" | jq -r '.[] | "| \(.file | gsub("\\|"; "\\\\|")) | \(.line) | \(.message | gsub("\\|"; "\\\\|")) |"'
           }
           INTRO_TABLE=$(build_table "$INTRO")
           REMOVED_TABLE=$(build_table "$REMOVED")
