wip

diff --git a/.github/workflows/phpstan.yml b/.github/workflows/phpstan.yml
--- a/.github/workflows/phpstan.yml
+++ b/.github/workflows/phpstan.yml
@@ -114,14 +114,10 @@ jobs:
         run: |
           jq -s 'def errs($json): $json.files|to_entries|map(.key as $file|.value.messages[]|{file:$file}+{message:.message,line:.line,ignorable:.ignorable,identifier:.identifier}); (.[1]|errs(.)) as $targetErrors | (.[0]|errs(.)) as $prErrors | $targetErrors | map(select(( $prErrors | index(.) ) == null))' pr-tip-phpstan.json target-branch-phpstan.json > introduced-errors.json || true
 
-      - name: Generate removed-errors.json
-        run: |
-          jq -s 'def errs($json): $json.files|to_entries|map(.key as $file|.value.messages[]|{file:$file}+{message:.message,line:.line,ignorable:.ignorable,identifier:.identifier}); (.[0]|errs(.)) as $prErrors | (.[1]|errs(.)) as $targetErrors | $prErrors | map(select(( $targetErrors | index(.) ) == null))' pr-tip-phpstan.json target-branch-phpstan.json > removed-errors.json || true
-
-      - name: Show summary of deltas
-        run: |
-          echo "Introduced files/errors:"
-          jq . introduced-errors.json || true
-          echo
-          echo "Removed files/errors:"
-          jq . removed-errors.json || true
+#      - name: Show summary of deltas
+#        run: |
+#          echo "Introduced files/errors:"
+#          jq . introduced-errors.json || true
+#          echo
+#          echo "Removed files/errors:"
+#          jq . removed-errors.json || true
