wip

diff --git a/.github/workflows/phpstan.yml b/.github/workflows/phpstan.yml
--- a/.github/workflows/phpstan.yml
+++ b/.github/workflows/phpstan.yml
@@ -95,10 +95,12 @@ jobs:
     steps:
       - name: Generate introduced-errors.json
         run: |
-          jq -s 'def errs($j): $j.files|to_entries|map({file:.key}+ .value.messages[])|map(tojson); (.[0]|errs(.)) as $pr | (.[1]|errs(.)) as $base | $pr | map(select(([ (.[1]|errs(.))[] ]|any(. == .; $pr[] )|not)) )|map(fromjson)' <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') > introduced-errors.json || true
+          jq -s 'def errs($j): $j.files|to_entries|map({file:.key}+.value.messages[]); (.[0]|errs(.)) as $pr|(.[1]|errs(.)) as $base|$pr|map(select($base|index(.)|not))' <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') > introduced-errors.json || true
+
       - name: Generate removed-errors.json
         run: |
-          jq -s 'def errs($j): $j.files|to_entries|map({file:.key}+ .value.messages[])|map(tojson); (.[0]|errs(.)) as $pr | (.[1]|errs(.)) as $base | $base | map(select(([ (.[0]|errs(.))[] ]|any(. == .; $base[] )|not)) )|map(fromjson)' <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') > removed-errors.json || true
+          jq -s 'def errs($j): $j.files|to_entries|map({file:.key}+.value.messages[]); (.[0]|errs(.)) as $pr|(.[1]|errs(.)) as $base|$base|map(select($pr|index(.)|not))' <(echo '${{ needs.phpstan.outputs.pr-tip-phpstan-json }}') <(echo '${{ needs.phpstan.outputs.target-branch-phpstan-json }}') > removed-errors.json || true
+
       - name: Show summary of deltas
         run: |
           echo "Introduced files/errors:"
@@ -106,6 +108,7 @@ jobs:
           echo
           echo "Removed files/errors:"
           jq . removed-errors.json || true
+
       - name: Build PR comment Markdown
         id: build-comment
         run: |
@@ -139,6 +142,7 @@ jobs:
             printf "%s\n" "$REMOVED_TABLE"
           } > phpstan-comment.md
           echo "comment-file=phpstan-comment.md" >> $GITHUB_OUTPUT
+
       - name: Create or update PHPStan comment
         uses: actions/github-script@v7
         with:
